### ISSUE TITLE
Implement a more complex set of Non-functional tests

### ISSUE THREAD

**Issue by BenDol** [GwtMaterialDesign/gwt-material-table#90]
## 2.0
* [x] Loading tests
* [x] Event tests
* [x] Renderer tests
* [x] Draw tests
* [x] Component tests
* [x] Sort tests
* [x] Clear/destroy tests
* [x] Infinite scroll tests
* [x] Data source tests
* [x] Row expansion tests

## 2.1
* [ ] Frozen column tests
